Repository axibase/axibase-charts-vscode, pull requests merged in 2018-09, with the labels that each got.

#1 Ignore column-* settings
  server/src/dictionary.json
  server/src/resources.ts
  server/src/test/spelling.test.ts
  server/src/validator.ts
Labels: invalid

#11 Download static files based on target server
  client/src/axibaseChartsProvider.ts
  client/src/extension.ts
Labels: enhancement

#27 Setting shadowing
  server/src/test/repetition.test.ts
  server/src/validator.ts
Labels: invalid

#29 Forbid endscript after script =
  server/src/test/script.test.ts
  server/src/validator.ts
  syntaxes/axibasecharts.tmLanguage.json
Labels: invalid

#33 Add 'script someJs' validation
  server/src/test/script.test.ts
  server/src/validator.ts
Labels: enhancement

#32 #31 User-agent header
  client/src/extension.ts
  client/src/util.ts
Labels: enhancement

#37 #36 add check for connection without auth
  client/src/axibaseChartsProvider.ts
  client/src/extension.ts
  client/src/util.ts
Labels: bug, done

#38 [Documentation]marketplace badge
  README.md
Labels: enhancement

#47 #34: Add multi-line script deprecation message
  server/src/test/repetition.test.ts
  server/src/test/script.test.ts
  server/src/validator.ts
Labels: enhancement

#49 #48: Make series-labels script
  server/src/dictionary.json
Labels: invalid

#50 Add '?' to de-alias regexp
  server/src/test/alias.test.ts
  server/src/validator.ts
Labels: invalid

#51 Add deprection message for thresholds
  package.json
  server/dictionary.json
  server/dictionary.schema.json
  server/src/resources.ts
  server/src/util.ts
  server/src/validator.ts
Labels: enhancement

#75 Make script = regexp multiline
  server/src/test/script.test.ts
  server/src/validator.ts
Labels: done

#72 Fix type errors
  server/src/resources.ts
  server/src/setting.ts
  server/src/test/type.test.ts
  server/src/util.ts
  server/src/validator.ts
  tslint.json
Labels: done

#78 Fix freemarker validator
  package.json
  server/src/test/spelling.test.ts
  server/src/validator.ts
Labels: done

#97 Remove console.log from client
  client/src/extension.ts
Labels: done

#95 Ignore script content
  server/src/test/script.test.ts
  server/src/validator.ts
Labels: pending

#100 [tag] section is depricated
  package.json
  server/src/messageUtil.ts
  server/src/test/alias.test.ts
  server/src/test/endList.test.ts
  server/src/test/forIn.test.ts
  server/src/test/freemarker.test.ts
  server/src/test/script.test.ts
  server/src/test/spelling.test.ts
  server/src/test/tags.test.ts
  server/src/test/undefinedVar.test.ts
  server/src/util.ts
  server/src/validator.ts
Labels: done

#108 Allow multi-line style
  server/dictionary.json
  server/src/test/repetition.test.ts
Labels: done

#109 Add a required setting test
  server/src/test/required.test.ts
Labels: done

#106 Allow detail statistic
  server/dictionary.json
  server/src/test/type.test.ts
Labels: done

#124 Remove diagnostic messages from dirty documents on closing
  .travis.yml
  .vscode/launch.json
  client/package-lock.json
  client/package.json
  client/src/extension.ts
  client/src/test/diagnostic.test.ts
  client/src/test/helper.ts
  client/src/test/index.ts
  client/src/util.ts
  client/testFixture/simple.config
  package-lock.json
  package.json
  scripts/e2e.sh
  server/package-lock.json
  tsconfig.base.json
Labels: done

#107 Allow last statistic and any percentile
  server/dictionary.json
  server/src/setting.ts
  server/src/test/type.test.ts
Labels: done

#112 Allow entity-expression as an alternative to entity
  server/src/resources.ts
  server/src/test/required.test.ts
Labels: done

#127 don't inform about setting name in tag section
  server/src/messageUtil.ts
  server/src/test/tags.test.ts
  server/src/validator.ts
Labels: done

#129 dynamic preview icon
  images/preview-inverted.svg
  package.json
Labels: done

#131 Simplify support
  server/src/completionProvider.ts
  server/src/field.ts
  server/src/formatter.ts
  server/src/jsDomCaller.ts
  server/src/resources.ts
  server/src/setting.ts
  server/src/test/alias.test.ts
  server/src/test/csv.test.ts
  server/src/test/endList.test.ts
  server/src/test/endfor.test.ts
  server/src/test/forIn.test.ts
  server/src/test/freemarker.test.ts
  server/src/test/if.test.ts
  server/src/test/indents.test.ts
  server/src/test/repetition.test.ts
  server/src/test/required.test.ts
  server/src/test/script.test.ts
  server/src/test/spelling.test.ts
  server/src/test/tags.test.ts
  server/src/test/type.test.ts
  server/src/test/undefinedVar.test.ts
  server/src/test/var.test.ts
  server/src/util.ts
  server/src/validator.ts
Labels: done

#118 Change settings title
  package.json
Labels: done

#16 Add settings descriptions
  server/descriptions.md
  server/src/hoverProvider.ts
  server/src/resources.ts
  server/src/server.ts
  server/src/test/hover.test.ts
  server/src/test/test.ts
Labels: done

#132 Fix indent between setting/variable name and equals sign
  server/src/formatter.ts
  server/src/test/indents.test.ts
Labels: done

#133 Update dictionary.json
  server/dictionary.json
Labels: done

#130 Validator: var object checks
  server/src/jsDomCaller.ts
  server/src/server.ts
  server/src/test/js.test.ts
  server/src/test/test.ts
  server/src/validator.ts
Labels: done

#138 version 1.0.9
  package.json
Labels: done

#143 Fix DiagnosticSeverity in JS tests
  server/src/test/js.test.ts
Labels: done

#135 Fix unknown variable when list name is concatenated with equals sign
  server/src/test/type.test.ts
  server/src/test/undefinedVar.test.ts
  server/src/validator.ts
Labels: done

#145 Remove extra dependencies
  client/package-lock.json
  client/package.json
  client/src/extension.ts
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
Labels: done

#142 Make mode one-line
  server/dictionary.json
Labels: done

#144 Add check on widget where a setting is defined
  server/src/setting.ts
  server/src/test/tags.test.ts
  server/src/validator.ts
Labels: done

#148 Remove Freemarker variable validation (#60)
  server/src/test/freemarker.test.ts
  server/src/test/spelling.test.ts
  server/src/test/type.test.ts
  server/src/validator.ts
Labels: done

#147 Add more info to the hover
  server/descriptions.md
  server/src/hoverProvider.ts
  server/src/resources.ts
  server/src/setting.ts
  server/src/test/hover.test.ts
Labels: done

#146 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: done
