Repository axibase/axibase-charts-vscode, pull requests merged in 2019-07, with the labels that each got.

#341 Update diff package
  client/package-lock.json
  client/package.json
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
Labels: done

#349 dictionary.json update
  server/dictionary.json
Labels: done

#350 Removed checks for forecast-style
  server/src/relatedSettingsRules/presenceValidation/requiredSettings.ts
  server/src/test/relatedSettings.test.ts
Labels: done

#329 Implemented TimeParser, moved Date validation to RelatedSettingsRule
  server/dictionary.json
  server/src/completionProvider.ts
  server/src/configTree/section.ts
  server/src/constants.ts
  server/src/defaultSetting.ts
  server/src/messageUtil.ts
  server/src/relatedSettingsRules/index.ts
  server/src/relatedSettingsRules/utils/condition.ts
  server/src/relatedSettingsRules/valueValidation/forecastEndTime.ts
  server/src/relatedSettingsRules/valueValidation/forecastStartTime.ts
  server/src/relatedSettingsRules/valueValidation/startEndTime.ts
  server/src/setting.ts
  server/src/test/startEndRelation.test.ts
  server/src/test/time/parseCalendarKeyword.test.ts
  server/src/test/time/parseDate.test.ts
  server/src/test/time/parseIntervalExpression.test.ts
  server/src/test/time/parseTime.test.ts
  server/src/test/type.test.ts
  server/src/time/index.ts
  server/src/time/timeParseError.ts
  server/src/time/timeParser.ts
  server/src/time/utils.ts
  server/src/util.ts
  server/src/validator.ts
Labels: done

#330 CSV unclosed syntax formatting
  server/src/completionProvider.ts
  server/src/constants.ts
  server/src/formatter.ts
  server/src/keywordHandler.ts
  server/src/messageUtil.ts
  server/src/regExpressions.ts
  server/src/setting.ts
  server/src/test/indents.test.ts
  server/src/textRange.ts
  server/src/validator.ts
Labels: bug, done

#352 Update `columns` property
  server/descriptions.md
  server/dictionary.json
Labels: done

#346 If condition variables support
  server/src/keywordHandler.ts
  server/src/test/ifCondition.test.ts
  server/src/validator.ts
Labels: done

#351 Don't add extra space in `>=` and `<=` relations
  server/src/constants.ts
  server/src/formatter.ts
  server/src/regExpressions.ts
  server/src/test/indents.test.ts
Labels: done

#342 Completions for sections in braces
  server/src/completionProvider.ts
Labels: done

#345 EndKeywords completion support
  server/src/completionProvider.ts
  server/src/constants.ts
  server/src/test/completionProvider.test.ts
  snippets/snippets.json
Labels: done

#355 Validate multiple javascript errors in file
  server/src/javaScriptValidator.ts
  server/src/test/js.multipleScripts.test.ts
Labels: bug, done

#357 Update repo links
  client/package.json
  server/package.json
Labels: done

#356 JavaScript formatting between `script` tags
  server/package-lock.json
  server/package.json
  server/src/formatter.ts
  server/src/regExpressions.ts
  server/src/test/scriptFormatting.test.ts
  snippets/snippets.json
Labels: done, enhancement

#361 Update lodash dependency
  client/package-lock.json
  client/package.json
  server/package-lock.json
  server/package.json
Labels: done

#362 Describe new-row-color property
  server/descriptions.md
  server/dictionary.json
Labels: done
